# Generated by Django 5.0.1 on 2024-03-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'city_name',
            },
        ),
        migrations.CreateModel(
            name='Physio_clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physio_clinic', models.CharField(max_length=40)),
                ('address', models.TextField(default='')),
                ('clinic_image', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'physio_clinic',
            },
        ),
        migrations.CreateModel(
            name='State_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'state_name',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city_name')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.AddField(
            model_name='city_name',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.state_name'),
        ),
    ]
