# Generated by Django 5.0.1 on 2024-03-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_make_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_appointment',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
